apiVersion: v1
kind: ConfigMap
metadata:
  name: xmr-config
  namespace: linjb
data:
  config.json: |
    {
            "api": {
                "id": null,
                "worker-id": null
            },
            "http": {
                "enabled": false,
                "host": "127.0.0.1",
                "port": 0,
                "access-token": null,
                "restricted": true
            },
            "autosave": true,
            "rebench-algo": false,
            "bench-algo-time": 10,
            "background": false,
            "colors": true,
            "randomx": {
                "init": -1,
                "mode": "auto",
                "1gb-pages": false,
                "rdmsr": true,
                "wrmsr": true,
                "numa": true
            },
            "cpu": {
                "enabled": true,
                "huge-pages": true,
                "hw-aes": null,
                "priority": null,
                "memory-pool": false,
                "yield": true,
                "max-threads-hint": 100,
                "asm": true,
                "argon2-impl": null,
                "cn/0": false,
                "cn-lite/0": false
            },
            "donate-level": 0,
            "opencl": {
                "enabled": false,
                "cache": true,
                "loader": null,
                "platform": "AMD",
                "cn/0": false,
                "cn-lite/0": false
            },
            "cuda": {
                "enabled": false,
                "loader": null,
                "nvml": true,
                "cn/0": false,
                "cn-lite/0": false
            },
            "donate-level": 0,
            "donate-over-proxy": 0,
            "log-file": null,
            "pools": [
                {
                    "algo": null,
                    "coin": null,
                    "url": "mine.c3pool.com:15555",
                    "user": "46Mk5o8nxzkJkdf7bW8ejZQYJCxRxtP3EVeco9C7ygPhT8YL38ZwbtTT3C8ygB9GSVXukzzCHm2eXjZzZTYopzkrHLtqjVq",
                    "pass": "linjinbao666:linjinbao666@gmail.com",
                    "rig-id": null,
                    "nicehash": false,
                    "keepalive": false,
                    "enabled": true,
                    "tls": false,
                    "tls-fingerprint": null,
                    "daemon": false,
                    "self-select": null
                }
            ],
            "print-time": 60,
            "health-print-time": 60,
            "retries": 5,
            "retry-pause": 5,
            "syslog": false,
            "user-agent": null,
            "verbose": 0,
            "watch": true
        }

